export const EM_CONSTRUCAO = "Em Construção"
export const ENV_FORNECEDOR = "Enviada ao Fornecedor"
export const AGUARDANDO_RECEBIMENTO = "Aguardando Recebimento"
export const EM_RECEBIMENTO = "Em Recebimento"
export const RECEBIDO = "Recebido"
